### ISSUE TITLE
When pushing a new view, the original view is still shown until the pushed view is interacted with

### ISSUE THREAD

**Issue by Nathan1258** [Mijick/NavigationView#34]
As shown in the video, the original view is still seen under the newly pushed view.
iOS 17.5.1 
Xcode version 5.4 (15F31d)

**Comment by FulcrumOne** [comment]
Hey. Sorry, its not user friendly at all (and I'm going to change it), but background color of every presented view is set to clear; that's why you see the view underneath. To "fix" it, please change a background colour globally to a selected colour
